// IMPORTANT: This file is auto-generated by Firebase Studio.
// Do not edit this file manually.

export const firebaseConfig = {
  "projectId": "studio-1292135550-ac661",
  "appId": "1:556356420320:web:e31ec7b646e6bc08498685",
  "apiKey": "AIzaSyCmG2Pn2s1rwe7EukcHeoLWLMxl4_-_MDQ",
  "authDomain": "studio-1292135550-ac661.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "556356420320",
  "storageBucket": "studio-1292135550-ac661.appspot.com"
};
